import Head from 'next/head'
import NavBar from './components/NavBar'
import React from 'react'
import DisplayComponent from './components/DisplayComponent'


export default function Dashboard() {

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <NavBar></NavBar>
      <DisplayComponent></DisplayComponent>
    </>
  )
}
