<<<<<<< HEAD
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PingPong',
  description: 'Generated by create next app',
}
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PingPong",
  description: "Simple pingpong game",
};
>>>>>>> origin/game_dashboard

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
  children: React.ReactNode
=======
  children: React.ReactNode;
>>>>>>> origin/game_dashboard
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
<<<<<<< HEAD
  )
=======
  );
>>>>>>> origin/game_dashboard
}
